// packages/vue/src/components/Tag/Tag.vue
<script setup lang="ts">
import { TagProps } from '@queo/core/src/types/tag';
import { computed } from 'vue';
const props = withDefaults(defineProps<TagProps>(), {
	size: 'sm',
	isActive: false,
});

const classes = computed(() => [
	'queo-tag',
	`queo-tag--${props.size}`,
	props.variant ? `queo-tag--${props.variant}` : '',
	{ 'queo-tag--active': props.isActive },
]);
</script>

<template>
	<span role="option" :aria-label="ariaLabel" :class="classes">
		<slot />
	</span>
</template>

// packages/react/src/components/Tag/tag.tsx
import { TagProps } from '@queo/core/src/types/tag';

export interface ReactTagProps extends TagProps {
	children: React.ReactNode;
	className?: string;
}

export function Tag({ size = 'size', variant, isActive, children, ariaLabel = '' }: ReactTagProps) {
	const classes = [
		'queo-tag',
		`queo-tag--${size}`,
		variant ? `queo-tag--${variant}` : '',
		isActive ? 'queo-tag--active' : '',
	]
		.filter(Boolean)
		.join(' ');

	return (
		<span role="option" aria-label={ariaLabel} className={classes}>
			{children}
		</span>
	);
}
