// examples/vue/src/App.vue
<script setup lang="ts">
import { Loader2, User } from 'lucide-vue-next';
</script>

<template>
	<div class="demo">
		<Button size="sm">Hello world</Button>
		<Button size="md">Hello world</Button>
		<Button size="lg">Hello world</Button>

		<Button variant="primary">Hello world</Button>
		<Button variant="secondary">Hello world</Button>
		<Button variant="outline">Hello world</Button>
		<Button variant="ghost">Hello world</Button>
		<Button variant="danger">Hello world</Button>

		<Button>
			<template #icon>
				<User />
			</template>
			User Settings
		</Button>
		<Button>
			User Settings
			<template #iconRight>
				<User />
			</template>
		</Button>
		<Button>
			<template #icon>
				<User />
			</template>
			User Settings
			<template #iconRight>
				<User />
			</template>
		</Button>
		<Button loading loading-position="left">
			<template #loadingIcon>
				<Loader2 class="animate-spin" />
			</template>
			Loading...
		</Button>
		<Button loading loading-position="right">
			Loading...
			<template #loadingIcon>
				<Loader2 class="animate-spin" />
			</template>
		</Button>
		<Button loading loading-position="center">
			<template #loadingIcon>
				<Loader2 class="animate-spin" />
			</template>
		</Button>
		<Button disabled>Disabled</Button>
	</div>
</template>

<style scoped>
.demo {
	display: flex;
	flex-direction: column;
	gap: 1rem;
	padding: 1rem;
}

.demo > div {
	display: flex;
	gap: 1rem;
}
</style>

// examples/react/src/App.tsx
import { Button } from '@queo/react';
import { Circle, Loader2, Trash, User } from 'lucide-react';

function App() {
	return (
		<>
			<Button size="sm">Hello world</Button>
			<Button size="md">Hello world</Button>
			<Button size="lg">Hello world</Button>

			<Button variant="primary">Hello world</Button>
			<Button variant="secondary">Hello world</Button>
			<Button variant="outline">Hello world</Button>
			<Button variant="ghost">Hello world</Button>
			<Button variant="danger">Hello world</Button>

			<Button icon={<User />}>User Settings</Button>
			<Button icon={<User />} iconRight={<Trash />}>
				User Settings
			</Button>

			<Button iconRight={<User />}>User Settings</Button>

			<Button loading loadingIcon={<Loader2 className="animate-spin" />}>
				User Settings
			</Button>
			<Button loading loadingPosition="left" loadingIcon={<Loader2 className="animate-spin" />}>
				User Settings
			</Button>
			<Button loading loadingPosition="center" loadingIcon={<Loader2 className="animate-spin" />}></Button>
			<Button disabled>User Settings</Button>
			<Button loading loadingPosition="center" loadingIcon={<Circle className="animate-pulse" />}></Button>
			<Button
				loading
				loadingPosition="center"
				variant="outline"
				loadingIcon={<Circle className="animate-bounce" />}
			></Button>
		</>
	);
}

export default App;
