// packages/react/src/components/Avatar/avatar.tsx
import { AvatarProps } from '@queo/core/src';
import { useState } from 'react';

export interface ReactAvatarProps extends AvatarProps {
	className?: string;
}

export function Avatar({
	src,
	alt = '',
	size = 'md',
	variant = 'circle',
	status,
	fallback,
	className,
}: ReactAvatarProps) {
	const [hasError, setHasError] = useState(false);

	const classes = ['queo-avatar', `queo-avatar--${size}`, `queo-avatar--${variant}`, className]
		.filter(Boolean)
		.join(' ');

	return (
		<div className={classes}>
			{src && !hasError ? (
				<img src={src} alt={alt} className="queo-avatar__image" onError={() => setHasError(true)} />
			) : (
				<span className="queo-avatar__fallback">{fallback || alt?.charAt(0).toUpperCase()}</span>
			)}
			{status && <span className={`queo-avatar__status queo-avatar__status--${status}`} />}
		</div>
	);
}

// packages/vue/src/components/Avatar/Avatar.vue
<script setup lang="ts">
import { AvatarProps } from '@queo/core/src/types/avatar';
import { computed, ref } from 'vue';
const props = withDefaults(defineProps<AvatarProps>(), {
	alt: '',
	size: 'md',
	variant: 'circle',
});

const hasError = ref(false);

const classes = computed(() => ['queo-avatar', `queo-avatar--${props.size}`, `queo-avatar--${props.variant}`]);
</script>

<template>
	<div :class="classes">
		<img v-if="src && !hasError" :src="src" :alt="alt" class="queo-avatar__image" @error="hasError = true" />
		<span v-else class="queo-avatar__fallback">
			{{ fallback || alt?.charAt(0).toUpperCase() }}
		</span>
		<span v-if="status" :class="['queo-avatar__status', `queo-avatar__status--${status}`]" />
	</div>
</template>
