// packages/vue/src/components/Button/Button.vue
<script setup lang="ts">
import { ButtonProps } from '@queo/core/src/index';
import { computed, useSlots } from 'vue';

const props = withDefaults(defineProps<ButtonProps>(), {
	size: 'sm',
	variant: 'primary',
	loading: false,
	disabled: false,
	loadingPosition: 'right',
});

const slots = useSlots();

const hasOnlyIcon = computed(() => {
	return !slots.default && (!!slots.icon || !!slots.loadingIcon);
});

const emit = defineEmits<{
	(e: 'click', event: MouseEvent): void;
}>();

const classes = computed(() => [
	'taylux-btn',
	`taylux-btn--${props.variant}`,
	`taylux-btn--${props.size}`,
	{
		'taylux-btn--icon-only': hasOnlyIcon.value,
	},
]);
</script>

<template>
	<button
		:class="classes"
		:aria-disabled="disabled || loading"
		:aria-label="ariaLabel"
		:aria-busy="loading"
		:disabled="disabled || loading"
		@click="emit('click', $event)"
	>
		<!-- Icon-only loading state -->
		<span v-if="loading && hasOnlyIcon" class="taylux-btn-icon-center" role="status">
			<slot name="loadingIcon"></slot>
		</span>

		<template v-else>
			<!-- Left loading icon -->
			<span
				v-if="loading && loadingPosition === 'left'"
				class="taylux-btn-icon-left"
				role="status"
				aria-hidden="true"
			>
				<slot name="loadingIcon" />
			</span>

			<!-- Left icon -->
			<span v-if="!loading && $slots.icon" class="taylux-btn-icon-left" aria-hidden="true">
				<slot name="icon" />
			</span>

			<!-- Button content -->
			<span
				v-if="$slots.default"
				class="taylux-btn-content"
				:class="{ 'sr-only': loading && !$slots.loadingIcon }"
			>
				<slot />
			</span>

			<!-- Right loading icon -->
			<span
				v-if="loading && loadingPosition === 'right'"
				class="taylux-btn-icon-right"
				role="status"
				aria-hidden="true"
			>
				<slot name="loadingIcon" />
			</span>

			<!-- Right icon -->
			<span v-if="!loading && $slots.iconRight" class="taylux-btn-icon-right" aria-hidden="true">
				<slot name="iconRight" />
			</span>
		</template>
	</button>
</template>

// packages/react/src/components/Button/button.tsx
import { ButtonProps } from '@queo/core/src/index';

export interface ReactButtonProps extends ButtonProps {
	children?: React.ReactNode;
	onClick?: (event: React.MouseEvent<HTMLButtonElement>) => void;
	className?: string;
	iconRight?: React.ReactNode;
}

export function Button({
	size = 'sm',
	variant = 'primary',
	loading = false,
	disabled = false,
	loadingPosition = 'right',
	children,
	icon,
	iconRight,
	loadingIcon,
	onClick,
	ariaLabel,
}: ReactButtonProps) {
	const hasOnlyIcon = !children && (!!icon || !!loadingIcon);

	const classes = [
		'taylux-btn',
		`taylux-btn--${variant}`,
		`taylux-btn--${size}`,
		hasOnlyIcon ? 'taylux-btn--icon-only' : '',
	]
		.filter(Boolean)
		.join(' ');

	const handleClick = (event: React.MouseEvent<HTMLButtonElement>) => {
		if (!disabled && !loading && onClick) {
			onClick(event);
		}
	};

	return (
		<button
			className={classes}
			aria-disabled={disabled || loading}
			aria-label={ariaLabel}
			aria-busy={loading}
			disabled={disabled || loading}
			onClick={handleClick}
		>
			{loading && hasOnlyIcon ? (
				<span className="taylux-btn-icon-center" role="status">
					{loadingIcon}
				</span>
			) : (
				<>
					{/* Loading icon left */}
					{loading && loadingPosition === 'left' && (
						<span className="taylux-btn-icon-left" role="status" aria-hidden="true">
							{loadingIcon}
						</span>
					)}

					{/* Regular icon left */}
					{!loading && icon && (
						<span className="taylux-btn-icon-left" aria-hidden="true">
							{icon}
						</span>
					)}

					{/* Content */}
					{children && (
						<span className={`taylux-btn-content ${loading && !loadingIcon ? 'sr-only' : ''}`}>
							{children}
						</span>
					)}

					{/* Loading icon right */}
					{loading && loadingPosition === 'right' && (
						<span className="taylux-btn-icon-right" role="status" aria-hidden="true">
							{loadingIcon}
						</span>
					)}

					{/* Regular icon right */}
					{!loading && iconRight && (
						<span className="taylux-btn-icon-right" aria-hidden="true">
							{iconRight}
						</span>
					)}
				</>
			)}
		</button>
	);
}
